
# Test the base URL
GET http://localhost:3000

###

# Login a customer
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "charlie@example.com",
  "password": "mypassword3"
}

###
-
# Create a Customer
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "firstName": "David",
  "lastName": "Mwangi",
  "email": "davidmwan1@example.com",
  "phoneNumber": "0796166200",
  "address": "Adison route"
}
