# Test the base URL
GET http://localhost:3000

### //**********************CUSTOMER******************//

# Create a Customer
POST http://localhost:3000/customer/newCustomer
Content-Type: application/json

{
  "firstName": "David",
  "lastName": "Mwangi",
  "email": "davidmwangi01@example.com",
  "phoneNumber": "0796166200",
  "address": "Adison route"
}

###

# Get all Customers
GET http://localhost:3000/customer/allCustomers

###

# Get Customers by id
GET http://localhost:3000/customer/3

###

# Update a Customer
PATCH  http://localhost:3000/customer/update/3
Content-Type: application/json

{
  "firstName": "David",
  "lastName": "Ranjoz",
  "email": "david.k.mwangi@example.com",
  "phoneNumber": "0796166200",
  "address": "Adison route"
}

###

# Delete Customers by id
DELETE  http://localhost:3000/customer/delete/2


### //********************CAR*****************************//

# Create a new car

POST http://localhost:3000/car/newcar
Content-Type: application/json

 { 
   "CarModel": "Nissan GTR-R35", 
   "year": "2024-09-01", 
   "color": "Silver", 
   "rentalRate": "578.00", 
   "availability": "yes", 
   "location": 5 
 }

###

# Get all cars from CarTable

GET http://localhost:3000/car/allCars

###

# Get car by ID
GET http://localhost:3000/car/4

###

# Update Car by ID
PUT  http://localhost:3000/car/update/7
Content-Type: application/json

{ 
   "year": "2025-03-01", 
   "color": "Black", 
   "rentalRate": "60.00", 
   "availability": "yes"
}

###

# Delete Car by ID

DELETE http://localhost:3000/car/delete/4

